### ISSUE TITLE
Are you gonna port this library to TypeScript somehow?

### ISSUE THREAD

**Issue by ProgrammingLife** [NateTheGreatt/bitECS#100]
Wish to see typescript version of this wonderful library. Are you gonna port this library to TypeScript?

I see here: https://github.com/NateTheGreatt/bitECS/blob/master/src/index.ts that TS port is coming soon but it was written more than a year ago 😀

**Comment by Utopiah** [comment]
See https://github.com/NateTheGreatt/bitECS/issues/57
