### ISSUE TITLE
Query operators

### ISSUE THREAD

**Issue by thomasgauthier** [NateTheGreatt/bitECS#104]
Is it possible to use operators like NOT, ANY, ALL in queries?

For example, in Unity one can do 

```c#
var query = new EntityQueryDesc
{
   None = new ComponentType[]{ typeof(Frozen) },
   All = new ComponentType[]{ typeof(RotationQuaternion) }
}
EntityQuery m_Group = GetEntityQuery(query);
```

**Comment by RemiMyrset** [comment]
An example where I need to get tilemap tile. It has a sprite, integer position but not float position.
```js
const query = defineQuery(
  [
    TilePositionComponent, // Vector2I
    SpriteComponent, // Sprite
    Not(PositionComponent), // Vector2
  ],
);
const entities = query(world);
```
Can be found in [Query](https://github.com/NateTheGreatt/bitECS/blob/master/docs/INTRO.md#-query) section of "Getting Started"
So you have the `Not` option, but not `All` and `Any` because that is frankly the default behavior(?).

**Comment by thomasgauthier** [comment]
Thank you. I had missed the `Not` in the docs. `All` is indeed the default behavior.

`Any` does not seem to be implemented, but using [TC39 Set Methods](https://tc39.es/proposal-set-methods/) it can be done easily.

<br>
The following fictious code 
<br />
<br />

```javascript
defineQuery(
  [
    TilePositionComponent
    Any(SpriteComponent, Color)
  ],
);
```

can be implemented as

```javascript

//set methods polyfill
import "core-js/features/set"

const tileQuery = defineQuery(
  [
    TilePositionComponent
  ],
);

const spriteQuery = defineQuery(
  [
    SpriteComponent,
  ],
);

const colorQuery = defineQuery(
  [
    Color
  ],
);

const entities = new Set(tileQuery(world))
  .intersects(
    new Set(spriteQuery(world))
    .union(new Set(colorQuery(world))
  );

```
