### ISSUE TITLE
null entity id 

### ISSUE THREAD

**Issue by Hootlook** [NateTheGreatt/bitECS#106]
I have a case where a player entity has a ref to a character unit as in player.unitEntity. There would be time where the player doesn't control any unit (got destroyed, unselected) so my reasoning would be to null this ref, so i set it to -1. Its ugly and a waste of memory. Is my reasoning wrong or is there a better way ?

**Comment by NateTheGreatt** [comment]
i suggest adding an entity to act as null/undefined, aka the "NOOP entity" (no-op / no-operation). i usually use `0` as my NOOP entity.

**Comment by Hootlook** [comment]
Its a good work around as long as you check for
