### ISSUE TITLE
Serialize/Deserialize a single entity with components?

### ISSUE THREAD

**Issue by Zetaphor** [NateTheGreatt/bitECS#108]
Maybe I'm thinking about this the wrong way, but I'm interested in serializing/deserializing a single entity with its associated components. I could do this through manual iteration over its components and associated properties, for which I have a definition I can reference, but I was hoping there is a native method that I'm just missing.

**Comment by caryoscelus** [comment]
one issue that may arise with this is if you have components with `Types.eid` fields since entity ids are world-dependent. i'm trying to build a custom serialization and run into issue that it seems hard to check for those outside the library

**Comment by NateTheGreatt** [comment]
new serialization:

https://github.com/NateTheGreatt/bitECS/tree/rc-0-4-0/docs/Serialization.md
