### ISSUE TITLE
Resizing smaller than the defaultSize always errors

### ISSUE THREAD

**Issue by krispya** [NateTheGreatt/bitECS#110]
In all cases I tested, resizing smaller than the defaultSize produced an error.
```js
const bitWorld = createWorld(); // Turns out default is 100000
setDefaultSize(5000); // Errors
```
Likewise if I tried setting it in createWorld, the components still instantiated with a default 100,000 entities:
```js
const bitWorld = createWorld(5000); // New components still are TypedArray(100000) 
```
Lastly, I tried with `defineComponent` but this also errors.
```js
// defaultSize is 100000
defineComponent({..}, 5000); // Errors
```
My workaround has been to start with the smallest world size and only grow when needed.
```js
const bitWorld = createWorld(1);
setDefaultSize(5000);
```

**Comment by NateTheGreatt** [comment]
resizing is now up to the user:

https://github.com/NateTheGreatt/bitECS/tree/rc-0-4-0
