### ISSUE TITLE
System.{enter,exit} sample code is incorrect.

### ISSUE THREAD

**Issue by Ithamar** [NateTheGreatt/bitECS#12]
In the registerSystem sample with enter/exit, it seems enter/exit is defined as a function directly receiving the entity ID (eid). However, the signature is very much like update, but instead a single eid is given instead of an array (e.g. you have to do `exit: (position, velocity) => eid => { do something with the entity id }` instead of the current example showing `exit: eid => { .... }`.

**Comment by NateTheGreatt** [comment]
thanks for catching this ^^. haven't kept up with the docs as well as i should have been. the API surface is changing soon (not too drastically), so i'll update the docs on next release (hopefully this weekend)

**Comment by Ithamar** [comment]
Lovely, looking forward to the new release! I'll close this issue for now, and simply recheck the docs once your new release drops.
