### ISSUE TITLE
How to get MAX number for the current type?

### ISSUE THREAD

**Issue by ProgrammingLife** [NateTheGreatt/bitECS#121]
Let's say we have a component containing fields:
```ts
i: Types.ui8,
r: Types.i16,
```
Is there a way to get the max number for the current type of the array's value? Something like: `length( Types.ui8 ) => 255`.

**Comment by cristw** [comment]
I think [this](https://developer.mozilla.org/es/docs/Web/JavaScript/Guide/Typed_arrays) might help you.
