### ISSUE TITLE
Component sizes, multiple worlds

### ISSUE THREAD

**Issue by n3vrax** [NateTheGreatt/bitECS#127]
I plan to build sort of an engine on top of this. The main concept is the idea of Scenes, which I decided to represent IWorld on their own.
I'm having some difficulties settings world sizes and component store sizes the same, especially if components are defined in a separate package. These leads me wondering if is bitECS actually meant to be used this way, and what would be the best approach in setting up multiple worlds and components to be reused across those. Still a bit confused about how component data is stored per world context.

Any suggestions would be greatly appreciated. Thanks!

**Comment by n3vrax** [comment]
Could resizeComponents be exported at least, so that we can adjust the sizes later on(after engine initialization)?

**Comment by NateTheGreatt** [comment]
new version allows components to be anything and associated in any way with any number of worlds:

https://github.com/NateTheGreatt/bitECS/tree/rc-0-4-0
