### ISSUE TITLE
provide ablity to check whether component field addresses eid

### ISSUE THREAD

**Issue by caryoscelus** [NateTheGreatt/bitECS#128]
a bit of context: i'm dealing with serialization rn, and find builtin serialization mechanism lacking in documentation. i'm getting some arraybuffer, but have no idea of its format. i haven't dug too far, but it does look like it's a binary format. i would like to have text-based serialization as alternative, so i'm building my own. with a bit of customizing `defineComponent` (along the lines of https://github.com/NateTheGreatt/bitECS/issues/111#issuecomment-1546972775), i'm able to jsonify entities, but in order to make proper (de)serialization i need to handle eids

it seems like whether a store contains eids or not can be determined by `$isEidType` field, but that symbol doesn't seem to be available for library users. can we have some way to query this information from outside library internals?

**Comment by pietrovismara** [comment]
You can use this "trick" to retrieve bitecs internal symbols:

```
const $localEntityLookup = Object.getOwnPropertySymbols(Component.property).find(
	(symbol) => symbol.toString() === Symbol('isEidType').toString(),
) as symbol;
```

It works also on `world` and on components.

**Comment by caryoscelus** [comment]
@pietrovismara this seems a bit too hacky to be reliable: anything not in API can be changed without warning. for now i simply forked repo to use in the project where i need this, but having official solution would still be better

**Comment by NateTheGreatt** [comment]
new serialization:

https://github.com/NateTheGreatt/bitECS/tree/rc-0-4-0/docs/Serialization.md
