### ISSUE TITLE
Expose `resetStore` to clear components

### ISSUE THREAD

**Issue by freeqaz** [NateTheGreatt/bitECS#145]
I have a game using Phaser where I am defining components every time we create a new scene.

This is a problem because components are kept around forever with no easy way to clear them.

As a fix, I can re-use the components when switching scenes... but then the state is dirty. It would be really nice to be able to call `resetStore(component)` and have that work.

Would it be reasonable to expose this? Or is there something else that I should be doing here? Thank you!

**Comment by epurban** [comment]
Having the same issue @NateTheGreatt, please let us know the best solution here!

**Comment by NateTheGreatt** [comment]
components can now be anything, but the consequence of that is resizing is fully up to the user:

https://github.com/NateTheGreatt/bitECS/tree/rc-0-4-0
