### ISSUE TITLE
Can I add code of conduct to this project?

### ISSUE THREAD

**Issue by vivek80801** [NateTheGreatt/bitECS#17]
I wanted to contribute to this project. I don't have skill set to contribute this project. I never developed any game. I am learning to code and I wanted to start my journey as web developer. Can I contribute to this project?

Can I add CODE_OF_CONDUCT.md and CONTRIBUTION.md to this project.

**Comment by NateTheGreatt** [comment]
this is an evolving personal project, but thanks for your interest!
