### ISSUE TITLE
NPM distribuable contains external binaries

### ISSUE THREAD

**Issue by ooflorent** [NateTheGreatt/bitECS#3]
I think something went wrong when publishing the package. `core-ecs` folder has been included into the NPM distribuable and contains many binaries (~25MB).

https://unpkg.com/browse/bitecs@0.1.1/core-ecs/node_modules/uWebSockets.js/

To prevent this, you could specify the `files` field in `package.json`.

**Comment by NateTheGreatt** [comment]
thanks for catching that, will fix. we use this in a larger project and apparently took some deps from it lol

**Comment by NateTheGreatt** [comment]
@ooflorent bitECS v0.1.2 published with a fix for this. thanks again for bringing this to my attention!
