### ISSUE TITLE
Error: Must use import to load ES Module

### ISSUE THREAD

**Issue by AdelNorberg** [NateTheGreatt/bitECS#30]
Hi! 
Sorry if I made a stupid mistake. My knowledge in node.js is weak :( But I don’t understand why  doesn’t see module build in your package. 
I am getting an error in the console:
![image](https://user-images.githubusercontent.com/24225624/126311943-231e678f-2734-4518-a9fe-e8177d5f2972.png)

Node v16.5.0
bitecs v0.3.15-1

package.json:
![image](https://user-images.githubusercontent.com/24225624/126312215-6f569f45-826a-4b28-aaab-f947efca0922.png)

tsconfig:
![image](https://user-images.githubusercontent.com/24225624/126312384-27feaad3-c58e-4af9-8c94-72a191f5e7c1.png)

**Comment by AdelNorberg** [comment]
![image](https://user-images.githubusercontent.com/24225624/126319691-ddda4309-1f60-439b-911d-5499d9aca85a.png)

If I remove this line everything works

**Comment by NateTheGreatt** [comment]
the best solution would be to switch from CommonJS modules (`require`) over to the more modern ES modules (`import`), as it is officially supported in the version of node you are using (16) 🙂

CommonJS:
```js
const { createWorld } = require('bitecs')
```

ES:
```js
import { createWorld } from 'bitecs'
```

**Comment by SupremeTechnopriest** [comment]
Also, you will have to either set `"type": "module"` in your package.json or name your files with the `.mjs` extension.

**Comment by AdelNorberg** [comment]
Thank you very much for your reply.
On the screenshot there is a property **{ type: "module" }**  and and I am using **import** instead of **require**. But the error still remains. At the same time, I have no problems with other packages

> the best solution would be to switch from CommonJS modules (`require`) over to the more modern ES modules (`import`), as it is officially supported in the version of node you are using (16) 🙂
> 
> CommonJS:
> 
> ```js
> const { createWorld } = require('bitecs')
> ```
> 
> ES:
> 
> ```js
> import { createWorld } from 'bitecs'
> ```
 
This is exactly what I do

**Comment by SupremeTechnopriest** [comment]
See my above comment.  You need to give your js files the `.mjs` extension or add `"type": "module"` to your own package json.

**Comment by AdelNorberg** [comment]
> See my above comment. You need to give your js files the `.mjs` extension or add `"type": "module"` to your own package json.

But I have added` type: "module"`. You can see it in the screenshot above

**Comment by SupremeTechnopriest** [comment]
Did you make sure to add it back to the bitecs package.json?  Are you using a bundle like webpack or rollup?

**Comment by NateTheGreatt** [comment]
> On the screenshot there is a property { type: "module" } and and I am using import instead of require. But the error still remains. At the same time, I have no problems with other packages (uWebSockets.js, three.js, and more)

I suspect you are using a bundler like webpack which is rewriting your `import` calls over to `require` calls in the bundled code. Am I correct in this assumption?

**Comment by AdelNorberg** [comment]
I use this package in two environments. In one of them, this package works. There Rollup.
In another, where there is nothing but ts (config on screenshots), an error occurs, which is in question in the issue


> Did you make sure to add it back to the bitecs package.json? Are you using a bundle like webpack or rollup?
Yeah. I removed node_modules so that there were no problems after changing package.json in node_modules

**Comment by SupremeTechnopriest** [comment]
can you add `"module": "ESNext"` to your tsconfig and try again?

**Comment by AdelNorberg** [comment]
> can you add "module": "ESNext" to your tsconfig's compilerOptions and try again? 

![image](https://user-images.githubusercontent.com/24225624/126850030-6c9d34f4-f84a-4879-b3e0-74ae53d9dd66.png)
  
With ESnext in ts config, other packages already stop working with the same error

**Comment by AdelNorberg** [comment]
If you look at other packages that work for me, then they do not have in package.json type: "module"

**Comment by hazulu** [comment]
I am having a similar issue as well-- I created a new TS project and tried using the library and was receiving the same error.

I was able to fix the issue if added type: module to my app's package.json, and compiled `tsc` rather than trying to run it. I ran the build with the following TSConfig:
![image](https://user-images.githubusercontent.com/12028362/126852503-1cf3ddfc-6c3c-4269-b4b3-57a5cf87fa29.png)
and this is the package.json:
![image](https://user-images.githubusercontent.com/12028362/126852564-3a48d94d-4fb6-47a7-9faa-98360fa56718.png)
(I did not run `npm run build`, I just used the `tsc` command)

**Comment by mrchantey** [comment]
same here, removing `"type": "module"` from the bitECS `package.json` did the trick (i'm using typescript+webpack)
ps awesome library! :)

**Comment by NateTheGreatt** [comment]
the transition from commonjs to es modules has been quite a mess haha. just fyi i haven't forgotten about this, still trying to figure out what the best solution is

**Comment by EnderShadow8** [comment]
I'm pretty sure there's a way to configure the package.json to provide different entry points depending on whether the module was `require`d or `import`ed, but I'm still figuring out the specfics of how that would work with TS and stuff

Best policy is to just use ESM since ESM can import CJS but not the other way around.

**Comment by EnderShadow8** [comment]
CJS can import ESM as follows:

```js
const importedModule = await import("./myModule.mjs")
```

Hope this solves the problem.
