### ISSUE TITLE
Queries get broken when removing then adding the same component within a system call

### ISSUE THREAD

**Issue by sebovzeoueb** [NateTheGreatt/bitECS#32]
I've found an unexpected behaviour which I believe to be a bug or at least in need of safeguarding against somehow.

I've boiled it down to queries getting broken if you remove then add the same component during the same system call without committing removals in between.

I made a repro project here so you can see it in action: https://github.com/sebovzeoueb/bitecs-not-query-test

Just load up index.html and open the dev console to see the output from the code. That repo's README has more detail on what's going on and why I believe it to be a bug.

**Comment by NateTheGreatt** [comment]
fixed in `0.3.16-5`

many thanks for the detailed report and example 🙏
