### ISSUE TITLE
Piping a query into a serializer doesn't work

### ISSUE THREAD

**Issue by sebovzeoueb** [NateTheGreatt/bitECS#40]
I followed the example from the docs, but using `pipe` with a query and a serializer is returning null for me.

See https://github.com/sebovzeoueb/bitecs-serializer-test the 3rd test is finding 2 entities in the query, but piping the query to the serializer is returning a null packet.

**Comment by NateTheGreatt** [comment]
fixed in `0.3.20` 👍
