### ISSUE TITLE
Example in Readme doesn't work

### ISSUE THREAD

**Issue by luetkemj** [NateTheGreatt/bitECS#42]
Awesome project! I'm excited to give this a go and build something with it :)

FYI the example on the README doesn't work. Running the code exactly as is results in the following error `Cannot destructure property 'time' of 'world' as it is undefined.`. Seems like `world` isn't getting passed into the pipes correctly. 

I can just run the systems manually to get around it for now.

```
setInterval(() => {
  movementSystem(world);
  timeSystem(world);
}, 16)
```

Thanks!

-----

Repro:
installed version `"bitecs": "^0.3.19-1"`
Run the code from the example in the README

Actual:
Throws error `Cannot destructure property 'time' of 'world' as it is undefined.`

Expected: 
To not throw an error

**Comment by NateTheGreatt** [comment]
thanks, good catch! just pushed a fix for that. i forgot to `return world` in the system functions 😅
