### ISSUE TITLE
suggestion: CHANGELOG.md

### ISSUE THREAD

**Issue by sebovzeoueb** [NateTheGreatt/bitECS#45]
It would be nice to have a changelog file documenting breaking changes to the API so we don't have to browse the docs to figure out what's different and why our code doesn't work anymore.

**Comment by NateTheGreatt** [comment]
yea, it's about time i add one. so far i've only added to the API, but deprecating `defineSystem` indeed calls for a changelog!

**Comment by NateTheGreatt** [comment]
finally added this!
