### ISSUE TITLE
String type?

### ISSUE THREAD

**Issue by luetkemj** [NateTheGreatt/bitECS#47]
I've never worked with TypedArrays before so I may be coming at this from the wrong direction. How would I define a component with string types? For example, suppose I want to define a "Name" component that stores the name of the entity - how would I do that?

**Comment by vegeta897** [comment]
This is addressed in the [FAQ](https://github.com/NateTheGreatt/bitECS/blob/master/docs/FAQ.md)

> Strings are expensive and usually unnecessary to have the ECS handle. Instead, create a mapping of integers to strings, and store the integers in the component data as a reference to a string. This makes string serialization minimal and fast.
