### ISSUE TITLE
v0.1.4 is broken

### ISSUE THREAD

**Issue by ooflorent** [NateTheGreatt/bitECS#6]
The release v0.1.4 does not work on node. The reason being the addition of `type` inside `package.json`.

```json
  "main": "./dist/index.min.js",
  "type": "module",
```

When using `type`, it indicates that `main` is an ES module.
Here is a backward compatible definition:

```js
  "type": "module",
  "main": "./dist/index.min.js",
  "exports": {
    "import": "./dist/index.es.js",
    "require": "./dist/index.min.js"
  }
```

**Comment by NateTheGreatt** [comment]
merged your PR for this
