### ISSUE TITLE
Question: Wouldn't this refactor be better?

### ISSUE THREAD

**Issue by ceoshikhar** [NateTheGreatt/bitECS#65]
I was reading the code and there is this function in `Entity.js`

```js
let resizeThreshold = () => globalSize - (globalSize / 5)
```

and I was thinking that wouldn't it be better if it was changed to 

```js
const getResizeThreshold = () => globalSize - (globalSize / 5)
```

so that it's more consistent with other functions like `getEntityCursor`, `getRemovedEntities`, `getGlobalSize` etc. Maybe there is reason why you did it the way it's done but while reading the code, I just thought it looked a little weird. Maybe I am wrong.

**Comment by ceoshikhar** [comment]
BTW If you do agree that this change would be better then please let me do this change. I would love to be a contributor.

**Comment by NateTheGreatt** [comment]
yea that is a better name for sure. however, all of this will be changing soon. instead of having a global memory, i have been adding in the concept of a `Universe` which will represent separate memory spaces, each universe having its own `resizeThreshold` and own set of worlds, etc

**Comment by ceoshikhar** [comment]
Got it. So I guess I won't be getting to have the pleasure of being a contributor to bitECS anytime soon. Thanks for the quick response. 😀

**Comment by grorp** [comment]
Will you have to register components not global but for universes then?

**Comment by NateTheGreatt** [comment]
> Will you have to register components not global but for universes then?

components are registered per-world

**Comment by grorp** [comment]
OK, thank you.
