### ISSUE TITLE
bug(serialization): resetGlobals required to reload a world

### ISSUE THREAD

**Issue by douglasduteil** [NateTheGreatt/bitECS#73]
Hi @NateTheGreatt 

That bitECS of yours is 🚀 for me.

I'm not sure I'm using it the proper way...
Anyway, I found a freaky behavior in the deserialize process, confusing old and new entities.

![bitecs0334-bug](https://user-images.githubusercontent.com/730511/152013007-24c1600a-ff3c-48e2-8aa1-1565bea9bd00.gif)

I narrow the mismatch to https://github.com/NateTheGreatt/bitECS/blob/53458fcd8163b74ecb99d81a3687297adc36ce0f/src/Entity.js#L70

After removing some entites, when reloading previous state, the deserialize function seems to reuse cursors that might be already present in packet to load 
https://github.com/NateTheGreatt/bitECS/blob/53458fcd8163b74ecb99d81a3687297adc36ce0f/src/Serialize.js#L343

That, I think, is giving this weird behavior when instead of loading 2 entries, it's loading the last of them with matching previously removed entities, and it allow "another load" of the same packet with dangling entities I guess (me lost a 🧠 )

![bitecs0334-bug3](https://user-images.githubusercontent.com/730511/152015005-9f7e5c67-ff76-4632-8f9d-6149b77538d6.gif)

One word : **WHY**

I simplify [the confusing demo above](https://codesandbox.io/s/bitecs-0-3-34-dynamic-item-list-mjjgj?file=/App.svelte) to an integration test to investigate :
```ts
// [...]

  it("should load 2 item after removing them", () => {
    // given
    const { assertItems, assertLength, more, less, save, load } = setup();

    // when
    // We add 2 items
    more();
    more();

    assertItems([
      [1, 100],
      [2, 101]
    ]);
    assertLength(2);

    // when
    // We save the state
    const pack = save();

    // when
    // We remove the 2 items
    less();
    less();

    // NOTE(douglasduteil): reseting the globals seems to hack the test
    // HACK(douglasduteil): use setDefaultSize to trigger a resetGlobals
    setDefaultSize(1e5);

    // when
    // We load the last state
    load(pack);

    // then
    assertItems([
      [0, 100],
      [1, 101]
    ]);
    assertLength(2);
  });


// [...]
```

I'm not sure about the `setDefaultSize` above...
It make the test pass but smells pretty wrong, I don't know ... (404 on 🧠 again)

Here is a test case sandbox to illustrate the behavior.
https://codesandbox.io/s/bitecs-0-3-34-serialize-test-b7uxt?file=/Serialize.test.js

Might be related to #67 

Thanks for the reading :)
Looking forward to new versions.

🧠 🛹

**Comment by EnderShadow8** [comment]
The serialiser doesn't capture a snapshot of the state at the time, but rather the diff between the current capture and the previous capture. An improved library is being developed here: https://github.com/Web-ECS/SoA-serialization

Related: #70

**Comment by douglasduteil** [comment]
Ooooh good to know
I'll look it up !
Thanks @EnderShadow8
