### ISSUE TITLE
Is this package maintained? 

### ISSUE THREAD

**Issue by ccfiel** [NateTheGreatt/bitECS#74]
I have notice the last update was last 2021. Is this package still maintained?

**Comment by NateTheGreatt** [comment]
@ccfiel yes indeed it is! i'm still here, just busy with a new job and a few side projects. i am currently in the process of refactoring `bitECS` into sub-modules which i have begun uploading to the new [Web-ECS](https://github.com/Web-ECS/) org. The plan for this org is to be a home for these sub-modules that the community can use.

right now there are two modules being actively worked on:

https://github.com/Web-ECS/do-serialization
this is the module i am refactoring `bitECS` serialization into. the API is not ECS-oriented, just designed for data-oriented structures in JS.

https://github.com/Web-ECS/do-three
this module is for Three.js interop between data-oriented structures

there are many more modules planned. stay tuned!

**Comment by ccfiel** [comment]
Thanks @NateTheGreatt @luetkemj. Great to know! :) I will be using this package to our game project

**Comment by zewa666** [comment]
Sorry for undigging this old issue @NateTheGreatt but I figured I'd ask here about the current affairs instead of creating a new ticket

**Comment by NateTheGreatt** [comment]
i'm in the process of implementing archetypes and relationships at the moment on the `archetypes` branch
