### ISSUE TITLE
getAllEntities seems to be gone but remains in typescript definitions

### ISSUE THREAD

**Issue by Shadowlauch** [NateTheGreatt/bitECS#83]
Not sure if I'm missing something, but when I try to call getAllEntities I get an error and looking at the getAllEntities itself returns undefined. Looking at the compiled code I could not find any mention of getAllEntities but the types still mention it.

**Comment by Shadowlauch** [comment]
Seems like this is related to #82

**Comment by NateTheGreatt** [comment]
sorry for the delay on merging that PR! i shall get a release out with this change soon

**Comment by fielding** [comment]
I see that I wasn't the only one looking to use `getAllEntities`! It has been merged (thx @NateTheGreatt), so this can be closed.

Cheers!

**Comment by pietrovismara** [comment]
I'm on v`0.3.38` from npm but I still can't use `getAllEntities`. Are you installing directly from github @fielding ?
