### ISSUE TITLE
`getAllEntities` is not a function

### ISSUE THREAD

**Issue by O4epegb** [NateTheGreatt/bitECS#89]
Using `v0.3.38` and it says that `getAllEntities` is not a function, and indeed there is no such function in dist files, but it's present in the `.d.ts` file.

It seems like some mismatch between what is published in npm and the source code?

**Comment by fielding** [comment]
I think you might be correct about it being a mismatch between what is published to npm and the source. Have you tried pointing the package to this repo to verify this? Something like...
```json
"bitecs": "github:NateTheGreatt/bitECS#master"
```

You actually just reminded me that I haven't updated one of my projects back to using the npm package haha, but on the upside `getAllEntities` is available since it points to my fork's dist branch.

**Comment by O4epegb** [comment]
> I think you might be correct about it being a mismatch between what is published to npm and the source. Have you tried pointing the package to this repo to verify this? Something like...
> 
> ```json
> "bitecs": "github:NateTheGreatt/bitECS#master"
> ```
> 
> You actually just reminded me that I haven't updated one of my projects back to using the npm package haha, but on the upside `getAllEntities` is available since it points to my fork's dist branch.

I don't think it's possible to point to Github because there is no `dist` folder checked in here?

**Comment by fielding** [comment]
herpderp! You're absolutely right, feel free to test using 

```

"bitecs": "github:fielding/bitECS#master"

```

so we can report back to @NateTheGreatt and verify that it is just a NPM mismatch

**Comment by O4epegb** [comment]
Yep, it works.

**Comment by AlexJWayne** [comment]
Just ran into this trying to make a test to ensure that an entity did not get created. Guess I'll use a query instead.

Weird that the types say its there.

Awesome, awesome, awesome lib, BTW. This is great fun to work in. Thank you.

**Comment by krispya** [comment]
Any updates on this?

**Comment by darkwebdev** [comment]
Sorry for another useless comment, just wanted to notify about the unresolved issue.

**Comment by NateTheGreatt** [comment]
```ts
query(world, [])
```

https://github.com/NateTheGreatt/bitECS/tree/rc-0-4-0
