### ISSUE TITLE
Storing array

### ISSUE THREAD

**Issue by bayou-brogrammer** [NateTheGreatt/bitECS#90]
Can't seem to figure out how to store an array of ui8. I have a component for FieldOfView which changes everytime the player moves. The visibleTiles just hold the idx [`(y as usize * self.width as usize) + x as usize`] to the relative tiles that are currently visible

```
export const FieldOfView = defineComponent(
  {
    radius: Types.ui8,
    isDirty: Types.ui8,
    visibleTiles: [Types.ui8],
  },
  5,
);
```

After this definition, I get unknown as the type
<img width="551" alt="CleanShot 2022-07-02 at 14 58 08@2x" src="https://user-images.githubusercontent.com/9278174/177014654-950c6d28-6328-477d-bbb2-40c3f8b7e20b.png">

Im probably missing something really simple. Or if there is a better way to store visible tiles let me know

**Comment by lecoqjacob** [comment]
errr so I was dumb. I needed to provide a number for the typed array after looking to the source.
<img width="547" alt="CleanShot 2022-07-02 at 15 07 47@2x" src="https://user-images.githubusercontent.com/9278174/177014868-a85d39bf-7a35-4988-b6c8-5e94db611d7b.png">


My question is what does that number actually do in terms of size? I printed the components to the console and it shows that visibileTiles is an array allocated to 1000 units.

<img width="420" alt="CleanShot 2022-07-02 at 15 08 54@2x" src="https://user-images.githubusercontent.com/9278174/177014884-6e00b07a-826c-403b-8e52-f5a7aaa4e0e5.png">

Is that standard or are we able to control how much allocation to start with? FieldOfView is a very spare component so I doubt it needs 1000

**Comment by vegeta897** [comment]
You can pass an integer as a second argument into `defineComponent` to control how large the data arrays are.

The number you use with your typed array definition controls how large the array is for each entity. With a size of 1 it's basically pointless compared to a single ui8 value. If it's meant to index the tiles on your map, then it needs to be as big as the map's total number of tiles.

**Comment by NateTheGreatt** [comment]
> My question is what does that number actually do in terms of size? I printed the components to the console and it shows that visibileTiles is an array allocated to 1000 units.
> Is that standard or are we able to control how much allocation to start with? FieldOfView is a very spare component so I doubt it needs 1000

This is due to a resizing bug on the current release. it should be fixed on `master`, pending release soon:tm:

**Comment by NateTheGreatt** [comment]
https://github.com/NateTheGreatt/bitECS/tree/rc-0-4-0
