### ISSUE TITLE
RemoveEntity() doesn't remove entity from Queries or Component

### ISSUE THREAD

**Issue by ScottLHelm** [NateTheGreatt/bitECS#94]
Calling RemoveEntity(world, eid) doesn't remove an entity from a query or the component array. Calling RemoveComponent() on the appropriate component does remove the entity from both though. Is this a bug with RemoveEntity() or am I calling the function incorrectly?

Thanks!

**Comment by speigg** [comment]
@ScottLHelm  this has been fixed on master; you should be able to test by installing directly from git 

"bitecs": "github:NateTheGreatt/bitECS#master"

**Comment by NateTheGreatt** [comment]
https://github.com/NateTheGreatt/bitECS/tree/rc-0-4-0
