### ISSUE TITLE
How to handle destroyed entities cleanup in central location

### ISSUE THREAD

**Issue by zewa666** [NateTheGreatt/bitECS#99]
Hey there,

I'd like to know what approach to take to perform some cleanup after an entity has been removed.
So e.g I have a map of <eid, sprites> where once the entity is removed, the according entry of the map should be deleted.

I thought about perhaps about instead of calling removeEntity directly instead do `addComponent(world, AboutToBeDead, eid)` and in the enterQuery of listening for AboutToBeDead, to perform the cleanup and call removeEntity afterwards. It feels like a workaround though.

**Comment by NateTheGreatt** [comment]
i think exit queries can help you here @zewa666 

```js
const Tag= defineComponent()
const tagQuery = defineQuery([Tag])
const exitedTagQuery = exitQuery(tagQuery)

exitedTagQuery.forEach(eid => {
  // do cleanup here
})
```

**Comment by NateTheGreatt** [comment]
i do create releases when i deem `master` branch to be stable. it's nearing stability, should have a release out in the next couple weeks.

**Comment by zewa666** [comment]
thanks for the response, I went with the wrapped removeEntity approach + a postcleanup on end game to clear all potential leftovers

**Comment by Hootlook** [comment]
> i think exit queries can help you here @zewa666
> 
> ```js
> const Sprite = defineComponent()
> const spriteQuery = defineQuery([Sprite])
> const exitedSpriteQuery = exitQuery(spriteQuery)
> 
> exitedSpriteQuery.forEach(eid => {
>   // cleanup sprites here
> })
> ```
> 
> not sure if that solves your issue or not.
> 
> i've heard some users of bitECS implement their own `Remove` tag & query so they can have more control over removals/recycling of IDs.
> 
> another strategy is to create your own `customRemoveEntity` function which calls removes all components from an entity and then adds the entity to a queue. the queue can be drained at the end of a frame, calling bitECS's `removeEntity` on each ID in the queue to safely hand back the EID to bitECS for recycling.

This is what i was looking for but are you sure this works ? I've tried it and the exit query keeps updating

**Comment by NateTheGreatt** [comment]
observers and manual entity recycling can be used to address this now:

https://github.com/NateTheGreatt/bitECS/tree/rc-0-4-0
